permissions: write-all # Equivalent to default permissions plus id-token: write
env:
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: imports/github-secrets
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: false
name: Test tap-pulumi-cloud

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: "1"
      NOXSESSION: tests-${{ matrix.python-version }}
      PIP_CONSTRAINT: ${{ github.workspace }}/.github/workflows/constraints.txt
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"

    steps:
    - name: Fetch secrets from ESC
      id: esc-secrets
      uses: pulumi/esc-action@v1
    - name: Checkout code
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5.1.1
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true

    - name: Upgrade pip
      run: |
        pip install pip
        pip --version

    - name: Install Poetry
      run: |
        pipx install poetry
        pipx inject poetry poetry-dynamic-versioning[plugin]
        poetry --version
        poetry self show plugins

    - name: Install Nox
      run: |
        pipx install nox
        pipx inject nox nox-poetry
        nox --version

    - name: Run tests
      env:
        TAP_PULUMI_CLOUD_TOKEN: ${{ steps.esc-secrets.outputs.TAP_PULUMI_CLOUD_TOKEN }}
        TAP_PULUMI_CLOUD_ORGANIZATIONS: ${{ steps.esc-secrets.outputs.TAP_PULUMI_CLOUD_ORGANIZATIONS }}
        TAP_PULUMI_CLOUD_START_DATE: ${{ steps.esc-secrets.outputs.TAP_PULUMI_CLOUD_START_DATE }}
      run: |
        nox
